export const PAYMENT_CONDITIONS = Object.freeze({
  PREPAID_VOUCHER: "PREPAID_VOUCHER",
  PAY_NOW: "PAY_NOW",
  PAY_LATER: "PAY_LATER",
  CAMPAIGN: "CAMPAIGN",
  MEMBERSHIP: "MEMBERSHIP",
  FREE_OF_CHARGE: "FREE_OF_CHARGE",
});

export const PAYMENT_CONDITION_VALUES = Object.freeze(Object.values(PAYMENT_CONDITIONS));
