export const ROLES = Object.freeze({
  RECEPTIONIST: "RECEPTIONIST",
  DRIVER: "DRIVER",
  KEY_CONTROLLER: "KEY_CONTROLLER",
  SUPERVISOR: "SUPERVISOR",
  OWNER: "OWNER",
});

export const STAFF_ROLES = Object.freeze([
  ROLES.RECEPTIONIST,
  ROLES.DRIVER,
  ROLES.KEY_CONTROLLER,
  ROLES.SUPERVISOR,
]);

