export const ROLES = Object.freeze({
  RECEPTIONIST: "RECEPTIONIST",
  DRIVER: "DRIVER",
  KEY_CONTROLLER: "KEY_CONTROLLER",
  SUPERVISOR: "SUPERVISOR",
  OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
  OWNER: "OWNER",
  SUPER_ADMIN: "SUPER_ADMIN",
});

export const STAFF_ROLES = Object.freeze([
  ROLES.RECEPTIONIST,
  ROLES.DRIVER,
  ROLES.KEY_CONTROLLER,
  ROLES.SUPERVISOR,
  ROLES.OPERATIONS_MANAGER,
  ROLES.SUPER_ADMIN,
]);
