export const TICKET_STATUS = Object.freeze({
  READY_TO_BE_PARKED: "READY_TO_BE_PARKED",
  PARKED_IN: "PARKED_IN",
  REQUESTED_FOR_DELIVERY: "REQUESTED_FOR_DELIVERY",
  ASSIGNED_FOR_DELIVERY: "ASSIGNED_FOR_DELIVERY",
  ON_THE_WAY: "ON_THE_WAY",
  ARRIVED_FOR_DELIVERY: "ARRIVED_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
});

const ALLOWED_TRANSITIONS = Object.freeze({
  [TICKET_STATUS.READY_TO_BE_PARKED]: [TICKET_STATUS.PARKED_IN],
  [TICKET_STATUS.PARKED_IN]: [TICKET_STATUS.REQUESTED_FOR_DELIVERY],
  [TICKET_STATUS.REQUESTED_FOR_DELIVERY]: [TICKET_STATUS.ASSIGNED_FOR_DELIVERY],
  [TICKET_STATUS.ASSIGNED_FOR_DELIVERY]: [TICKET_STATUS.ON_THE_WAY],
  [TICKET_STATUS.ON_THE_WAY]: [TICKET_STATUS.ARRIVED_FOR_DELIVERY, TICKET_STATUS.DELIVERED],
  [TICKET_STATUS.ARRIVED_FOR_DELIVERY]: [TICKET_STATUS.DELIVERED],
  [TICKET_STATUS.DELIVERED]: [],
});

export function canTransitionStatus(fromStatus, toStatus) {
  if (!fromStatus || !toStatus) {
    return false;
  }

  if (fromStatus === toStatus) {
    return true;
  }

  return ALLOWED_TRANSITIONS[fromStatus]?.includes(toStatus) || false;
}
