export const TICKET_STATUS = Object.freeze({
  NEW_TRANSACTION_CREATED: "NEW_TRANSACTION_CREATED",
  READY_TO_BE_PARKED: "READY_TO_BE_PARKED",
  PARKED_IN: "PARKED_IN",
  REQUESTED_FOR_DELIVERY: "REQUESTED_FOR_DELIVERY",
  ASSIGNED_FOR_DELIVERY: "ASSIGNED_FOR_DELIVERY",
  ARRIVED_FOR_DELIVERY: "ARRIVED_FOR_DELIVERY",
  CLOSED: "CLOSED",

  // Backward compatibility for the current controller implementation.
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
  NOT_PARKED: "NOT_PARKED",
  PARKED: "PARKED",
  RETRIEVAL_REQUESTED: "RETRIEVAL_REQUESTED",
  ON_THE_WAY: "ON_THE_WAY",
  DELIVERED: "DELIVERED",
  PAID: "PAID",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  RE_PARKED: "RE_PARKED",
  DISPATCHED: "DISPATCHED",
});

const ALLOWED_TRANSITIONS = Object.freeze({
  [TICKET_STATUS.NEW_TRANSACTION_CREATED]: [TICKET_STATUS.READY_TO_BE_PARKED],
  [TICKET_STATUS.READY_TO_BE_PARKED]: [TICKET_STATUS.PARKED_IN],
  [TICKET_STATUS.PARKED_IN]: [TICKET_STATUS.REQUESTED_FOR_DELIVERY],
  [TICKET_STATUS.REQUESTED_FOR_DELIVERY]: [TICKET_STATUS.ASSIGNED_FOR_DELIVERY],
  [TICKET_STATUS.ASSIGNED_FOR_DELIVERY]: [TICKET_STATUS.ON_THE_WAY],
  [TICKET_STATUS.ON_THE_WAY]: [TICKET_STATUS.ARRIVED_FOR_DELIVERY, TICKET_STATUS.DELIVERED],
  [TICKET_STATUS.ARRIVED_FOR_DELIVERY]: [TICKET_STATUS.DELIVERED],
  [TICKET_STATUS.DELIVERED]: [TICKET_STATUS.CLOSED, TICKET_STATUS.PAID, TICKET_STATUS.COMPLETED],
  [TICKET_STATUS.CLOSED]: [],

  [TICKET_STATUS.CREATED]: [TICKET_STATUS.ASSIGNED, TICKET_STATUS.CANCELLED],
  [TICKET_STATUS.ASSIGNED]: [TICKET_STATUS.NOT_PARKED, TICKET_STATUS.CANCELLED],
  [TICKET_STATUS.NOT_PARKED]: [TICKET_STATUS.PARKED, TICKET_STATUS.RE_PARKED, TICKET_STATUS.DISPATCHED, TICKET_STATUS.CANCELLED],
  [TICKET_STATUS.PARKED]: [TICKET_STATUS.RETRIEVAL_REQUESTED, TICKET_STATUS.RE_PARKED, TICKET_STATUS.DISPATCHED],
  [TICKET_STATUS.RETRIEVAL_REQUESTED]: [TICKET_STATUS.ON_THE_WAY, TICKET_STATUS.CANCELLED],
  [TICKET_STATUS.ON_THE_WAY]: [TICKET_STATUS.DELIVERED],
  [TICKET_STATUS.DELIVERED]: [TICKET_STATUS.PAID, TICKET_STATUS.COMPLETED],
  [TICKET_STATUS.PAID]: [TICKET_STATUS.COMPLETED],
  [TICKET_STATUS.RE_PARKED]: [TICKET_STATUS.PARKED],
  [TICKET_STATUS.DISPATCHED]: [TICKET_STATUS.COMPLETED],
  [TICKET_STATUS.CANCELLED]: [],
  [TICKET_STATUS.COMPLETED]: [],
});

export function canTransitionStatus(fromStatus, toStatus) {
  if (!fromStatus || !toStatus) {
    return false;
  }

  if (fromStatus === toStatus) {
    return true;
  }

  return ALLOWED_TRANSITIONS[fromStatus]?.includes(toStatus) || false;
}
