services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mr_valet_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: ${PORT:-4000}
      REDIS_URL: redis://redis:6379
    ports:
      - "5001:${PORT:-5000}"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: mr_valet_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
