import { Router } from "express";
import healthRoutes from "./health.routes.js";
import authRoutes from "./auth.routes.js";
import ticketRoutes from "./ticket.routes.js";
import userRoutes from "./user.routes.js";
import branchRoutes from "./branch.routes.js";
import attendanceRoutes from "./attendance.routes.js";
import whatsappRoutes from "./whatsapp.routes.js";
import chatRoutes from "./chat.routes.js";
import employeeRoutes from "./employee.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import subscriptionRoutes from "./subscription.routes.js";
import serviceRoutes from "./service.routes.js";
import paymentRoutes from "./payment.routes.js";
import paperTicketRoutes from "./paperTicket.routes.js";
import nfcTagRoutes from "./nfcTag.routes.js";
import incidentReportRoutes from "./incidentReport.routes.js";
import notificationRoutes from "./notification.routes.js";

const router = Router();

router.use("/v1/health", healthRoutes);
router.use("/v1/auth", authRoutes);
router.use("/v1/tickets", ticketRoutes);
router.use("/v1/users", userRoutes);
router.use("/v1/branches", branchRoutes);
router.use("/v1/attendance", attendanceRoutes);
router.use("/v1/whatsapp", whatsappRoutes);
router.use("/v1/chat", chatRoutes);
router.use("/v1/employees", employeeRoutes);
router.use("/v1/dashboard", dashboardRoutes);
router.use("/v1/subscriptions", subscriptionRoutes);
router.use("/v1/services", serviceRoutes);
router.use("/v1/payments", paymentRoutes);
router.use("/v1/paper-tickets", paperTicketRoutes);
router.use("/v1/nfc-tags", nfcTagRoutes);
router.use("/v1/incident-reports", incidentReportRoutes);
router.use("/v1/notifications", notificationRoutes);

export default router;
